/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import java.awt.Point;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import komunikacija.Komunikacija;
import model.SkriveniBroj;
import operacije.Operacije;
import transfer.KlijentskiZahtev;
import transfer.ServerskiOdgovor;

/**
 *
 * @author Anđela
 */
public class KlijentskaForma extends javax.swing.JFrame {

    int brojPokusaja = 0;
    int brojPogodaka = 0;
    int sifra = 0;
    int cifra1, cifra2, cifra3 = 0;

    /**
     * Creates new form KlijentskaForma
     */
    public KlijentskaForma() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Prva kolona", "Druga kolona", "Treca kolona"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(119, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        brojPokusaja++;
        if (brojPokusaja > 5) {
            JOptionPane.showMessageDialog(this, "MAKSIMALNI BROJ POKUSAJA JE 5, IZGUBILI STE");
            KlijentskiZahtev kz = new KlijentskiZahtev(null, Operacije.NOVA_IGRA);
            Komunikacija.getKmk().posaljiZahtev(kz);
            Komunikacija.getKmk().prekini();
            this.dispose();
            return;
        }
        JTable tabela = (JTable) evt.getSource();
        Point point = evt.getPoint();
        int red = tabela.rowAtPoint(point);
        int kolona = tabela.columnAtPoint(point);
        if (red != -1 && kolona!= -1){
        SkriveniBroj sb = new SkriveniBroj(-1, red, kolona);
            KlijentskiZahtev kz = new KlijentskiZahtev(sb, Operacije.POGADJANJE_CIFRE);
            Komunikacija.getKmk().posaljiZahtev(kz);
            /////////////////////////////////////////////////////////////////////////
            ServerskiOdgovor so = (ServerskiOdgovor) Komunikacija.getKmk().primiOdgovor();
            SkriveniBroj sbOdg = (SkriveniBroj) so.getOdgovor();
            if (sbOdg == null) {
                JOptionPane.showMessageDialog(this, "Ne postoji broj na tom polju");
                return;
            } else {
                tabela.getModel().setValueAt(sbOdg.getVrednost(), red, kolona);
                brojPogodaka++;
                if (brojPogodaka == 1) {
                    cifra1 = sbOdg.getVrednost();
                } else if (brojPogodaka == 2) {
                    cifra2 = sbOdg.getVrednost();
                } else if (brojPogodaka == 3) {
                    cifra3 = sbOdg.getVrednost();
                }
                int najveci = Math.max(cifra1, Math.max(cifra2, cifra3));
                int najmanji = Math.min(cifra1, Math.min(cifra2, cifra3));
                int srednji = cifra1 + cifra2 + cifra3 - najveci - najmanji;
                sifra = najveci * 100 + srednji * 10 + najmanji;
                if (brojPogodaka == 3) {
                    JOptionPane.showMessageDialog(this, "POBEDILI STE, sifra je " + sifra);
                    this.dispose();
                    return;
                }
            }
        }
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KlijentskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KlijentskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KlijentskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KlijentskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KlijentskaForma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
